theme = "solarized-dark"
#theme = "gruvbox-dark"

[icons]
name = "awesome"
[icons.overrides]


[[block]]
block = "sound"

[[block]]
block = "custom"
command = ''' if [ "`optimus-manager --print-mode | grep nvidia`" ];  then echo 'NVIDIA'; else echo 'INTEL'; fi ''' 
interval = 99999999

[[block]]
block = "disk_space"
info_type = "available"
unit = "GB"
interval = 20
format = "{icon} {available} {unit}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mupi}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "custom"
command = '''echo  $(ip route | grep '^[0-9]' | sed -E 's/.*src\s([0-9\.]*).*/\1/' ) : $(curl ipinfo.io/ip)''' 
interval = 120

[[block]]
block = "time"
interval = 60
format = "%d/%m %R"

[[block]]
block = "bluetooth"
mac = "90:E2:02:BC:37:E6"

[[block]]
block = "battery"
#format = "{percentage}% {time}"
format = "{percentage}%"
driver = "upower"
device = "BAT1"

